### ISSUE TITLE
Does not work for minimal js script

### ISSUE THREAD

**Issue by sdeleon28** [markwoodhall/vim-aurepl#1]
**To reproduce:**

* Install as usual with vim-plug
* Create `file1.js` and open it with Vim
* Enter `1+1;` in the first line
* `:LineToRepl`

**Result:**

![screen shot 2017-06-18 at 4 48 59 pm](https://user-images.githubusercontent.com/633057/27263757-54cbb36c-5446-11e7-9f81-aeef32728e6a.png)

**Note:** Using NeoVim

**Comment by markwoodhall** [comment]
Thanks for the issue report, and for even trying this, it's very new and not particularly "finished" at the moment. 

Would you be able to let me know which version of node is installed? For JavaScript `:LineToRepl` will result in a call to node, what does running this `node --eval "$(cat ./file1.js)" --print` output for you?
